let qrcode = new QRCode(document.querySelector(".qrcode"));

qrcode.makeCode("Hello ,I'm Pradeepthi. This QR is generated by me!!");

function generateQr() {

if (

document.querySelector("input").value ===" " ||
document.querySelector("input").value ===" "){
alert("Input Field Is Empty"); }

else {

qrcode.makeCode(document.querySelector("input").value);

}
}